base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

adapter: qlora
lora_model_dir:

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

datasets:
  - path: ./instruct-data
    type:
      system_prompt: ""
      field_system: ""
      field_instruction: "prompt"
      field_output: "response"
      format: "{instruction}"
      no_input_format: "{instruction}"
  - path: databricks/databricks-dolly-15k
    type:
      system_prompt: "Below is an instruction that describes a task. The task may have additional context. Write a response that appropriately completes the request.\n\n"
      system_format: ""
      field_system: ""
      field_instruction: instruction
      field_input: context
      field_output: response

      format: |-
        ### Instruction: {instruction}
        ### Context: {input}
        ### Response: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Response: 
dataset_prepared_path:
val_set_size: 0.01

output_dir: ./out/Mistral-7B-sft-v1

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 8
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 250
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"